name: AzureML Download Model
description: Downloads an AzureML Model

inputs:
  model-name:
    description: Name of the model to be downloaded
    required: true
  resource-group:
    description: The name of the Resource Group
    required: true
  spn-id:
    description: The Service Principal ID
    required: true
  spn-pwd:
    description: The Service Principal Password
    required: true
  subs-id:
    description: The Subscription ID
    required: true
  tenant-id:
    description: The Tenant ID of your subscription
    required: true
  workspace-name:
    description: The Name of your Workspace
    required: true
outputs:
  filepath:
    description: The Filepath of the downloaded model
    value: ${{ steps.download-model.outputs.filepath }}
  
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ssc-dsai/azureml-download-model-github-action
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install Dependencies
      run: pip install azureml-core
      shell: bash

    - name: Download Model
      id: download-model
      run: |
        filepath=$(python ./download_model.py)
        echo "::set-output name=filepath::$(echo $filepath)"
      shell: bash
      env:
        MODEL_NAME: ${{ inputs.model-name }}
        RESOURCE_GROUP: ${{ inputs.resource-group }}
        SPN_ID: ${{ inputs.spn-id }}
        SPN_PWD: ${{ inputs.spn-pwd }}
        SUBS_ID: ${{ inputs.subs-id }}
        TENANT_ID: ${{ inputs.tenant-id }}
        WORKSPACE_NAME: ${{ inputs.workspace-name }}