name: AzureML Download Model
description: Downloads an AzureML Model

inputs:
  model-name:
    description: Name of the model to be downloaded
    required: true
  spn-id:
    description: The Service Principal ID
    required: true
  spn-pwd:
    description: The Service Principal Password
    required: true
  resource-group:
    description: The Resource group where the model is located
    required: true
  tenant-id:
    description: The Tenant ID of your subscription
    required: true
  workspace-name:
    description: The Worspace Name where the model is located
    required: true

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az login --service-principal -u ${{ inputs.spn-id }} -p ${{ inputs.spn-pwd }} --tenant ${{ inputs.tenant-id }}
          az extension add -n azure-cli-ml
          az configure --defaults group=${{ inputs.resource-group }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        inlineScript: |
          ${{ github.action_path }}/download_model.sh
      env:
        MODEL_NAME: ${{ inputs.model-name }}
        WORKSPACE_NAME: ${{ inputs.workspace-name }}