name: AzureML Download Model
description: Downloads an AzureML Model

inputs:
  config:
    description: Json Object with the Subscription ID, Resource group name, Workspace name, and Location
    required: true
  model-name:
    description: Name of the model to be downloaded
    required: true
  spn-id:
    description: The Service Principal ID
    required: true
  spn-pwd:
    description: The Service Principal Password
    required: true
  tenant-id:
    description: The Tenant ID of your subscription
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install Dependencies
      run: pip install azureml-core
      shell: bash

    - name: Download Model
      run: python download_model.py
      shell: bash
      env:
        CONFIG: ${{ inputs.config }}
        MODEL_NAME: ${{ inputs.model-name }}
        SPN_ID: ${{ inputs.spn-id }}
        SPN_PWD: ${{ inputs.spn-pwd }}
        TENANT_ID: ${{ inputs.tenant-id }}
