name: Download AzureML Model Test

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  download-model: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download AzureML Model
      id: download-model
      uses: ssc-dsai/azureml-download-model-github-action@main
      with:
        model-name: ${{ secrets.MODEL_NAME }}
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        spn-id: ${{ secrets.SPN_ID}}
        spn-pwd: ${{ secrets.SPN_PWD }}
        subs-id: ${{ secrets.SUBS_ID }}
        tenant-id: ${{ secrets.TENANT_ID}}
        workspace-name: ${{ secrets.WORKSPACE_NAME }}

    - name: Test file path
      run: |
        echo ${{ steps.download-model.outputs.filepath }}
        ls -a