name: Download AzureML Model Test

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  download-model: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Download AzureML Model
      uses: SSC-DSAI/azureml-download-model-github-action@main
      with:
        azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
        model-name: ${{ secrets.MODEL_NAME }}
        workspace-name: "ScScCPS-DSAI-Lab-dev-mlw"
        resource-group: "ScSc-DSAI-Lab-dev-rg"